<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaktabTaha.Domain\MaktabTaha.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\BaseEntities\area\Command\Create\" />
    <Folder Include="Features\BaseEntities\area\Command\Delete\" />
    <Folder Include="Features\BaseEntities\area\Command\Update\" />
    <Folder Include="Features\BaseEntities\area\Query\Single\" />
    <Folder Include="Features\BaseEntities\bank\Command\Create\" />
    <Folder Include="Features\BaseEntities\bank\Command\Delete\" />
    <Folder Include="Features\BaseEntities\bank\Command\Update\" />
    <Folder Include="Features\BaseEntities\bank\Query\Single\" />
    <Folder Include="Features\BaseEntities\caseType\Command\Create\" />
    <Folder Include="Features\BaseEntities\caseType\Command\Delete\" />
    <Folder Include="Features\BaseEntities\caseType\Command\Update\" />
    <Folder Include="Features\BaseEntities\caseType\Query\Single\" />
    <Folder Include="Features\BaseEntities\charityMainRole\Command\Create\" />
    <Folder Include="Features\BaseEntities\charityMainRole\Command\Delete\" />
    <Folder Include="Features\BaseEntities\charityMainRole\Command\Update\" />
    <Folder Include="Features\BaseEntities\charityMainRole\Query\Single\" />
    <Folder Include="Features\BaseEntities\city\Command\Create\" />
    <Folder Include="Features\BaseEntities\city\Command\Delete\" />
    <Folder Include="Features\BaseEntities\city\Command\Update\" />
    <Folder Include="Features\BaseEntities\city\Query\Single\" />
    <Folder Include="Features\BaseEntities\educationLevel\Command\Create\" />
    <Folder Include="Features\BaseEntities\educationLevel\Command\Delete\" />
    <Folder Include="Features\BaseEntities\educationLevel\Command\Update\" />
    <Folder Include="Features\BaseEntities\educationLevel\Query\Single\" />
    <Folder Include="Features\BaseEntities\educationStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\educationStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\educationStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\educationStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\employmentStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\employmentStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\employmentStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\employmentStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\goodWorkType\Command\Create\" />
    <Folder Include="Features\BaseEntities\goodWorkType\Command\Delete\" />
    <Folder Include="Features\BaseEntities\goodWorkType\Command\Update\" />
    <Folder Include="Features\BaseEntities\goodWorkType\Query\Single\" />
    <Folder Include="Features\BaseEntities\houeHeadStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\houeHeadStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\houeHeadStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\houeHeadStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\housingStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\housingStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\housingStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\housingStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\job\Command\Create\" />
    <Folder Include="Features\BaseEntities\job\Command\Delete\" />
    <Folder Include="Features\BaseEntities\job\Command\Update\" />
    <Folder Include="Features\BaseEntities\job\Query\Single\" />
    <Folder Include="Features\BaseEntities\nationality\Command\Create\" />
    <Folder Include="Features\BaseEntities\nationality\Command\Delete\" />
    <Folder Include="Features\BaseEntities\nationality\Command\Update\" />
    <Folder Include="Features\BaseEntities\nationality\Query\Single\" />
    <Folder Include="Features\BaseEntities\orphanStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\orphanStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\orphanStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\orphanStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\physicalStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\physicalStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\physicalStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\physicalStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\privatenessStatus\Command\Create\" />
    <Folder Include="Features\BaseEntities\privatenessStatus\Command\Delete\" />
    <Folder Include="Features\BaseEntities\privatenessStatus\Command\Update\" />
    <Folder Include="Features\BaseEntities\privatenessStatus\Query\Single\" />
    <Folder Include="Features\BaseEntities\province\Command\Create\" />
    <Folder Include="Features\BaseEntities\province\Command\Delete\" />
    <Folder Include="Features\BaseEntities\province\Command\Update\" />
    <Folder Include="Features\BaseEntities\province\Query\Single\" />
    <Folder Include="Features\BaseEntities\relation\Command\Create\" />
    <Folder Include="Features\BaseEntities\relation\Command\Delete\" />
    <Folder Include="Features\BaseEntities\relation\Command\Update\" />
    <Folder Include="Features\BaseEntities\relation\Query\Single\" />
    <Folder Include="Features\BaseEntities\religon\Command\Create\" />
    <Folder Include="Features\BaseEntities\religon\Command\Delete\" />
    <Folder Include="Features\BaseEntities\religon\Command\Update\" />
    <Folder Include="Features\BaseEntities\religon\Query\Single\" />
    <Folder Include="Features\BaseEntities\requestType\Command\Create\" />
    <Folder Include="Features\BaseEntities\requestType\Command\Delete\" />
    <Folder Include="Features\BaseEntities\requestType\Command\Update\" />
    <Folder Include="Features\BaseEntities\requestType\Query\Single\" />
    <Folder Include="Features\BaseEntities\skill\Command\Create\" />
    <Folder Include="Features\BaseEntities\skill\Command\Delete\" />
    <Folder Include="Features\BaseEntities\skill\Command\Update\" />
    <Folder Include="Features\BaseEntities\skill\Query\Single\" />
    <Folder Include="Features\BaseEntities\unemploymentReason\Command\Create\" />
    <Folder Include="Features\BaseEntities\unemploymentReason\Command\Delete\" />
    <Folder Include="Features\BaseEntities\unemploymentReason\Command\Update\" />
    <Folder Include="Features\BaseEntities\unemploymentReason\Query\Single\" />
  </ItemGroup>

</Project>
